#!/usr/bin/env python

from repo_maker import create_repo
import typer

if __name__ == "__main__":
    typer.run(create_repo)
    repo_name = input("What is the name of the repo? ")

    assert (
        isinstance(repo_name, str) and len(repo_name) > 0
    ), "Please enter a repo name!"

    create_repo(repo_name)
